---
build_from:
  aarch64: docker.io/library/influxdb:2.6.1-alpine
  amd64: docker.io/library/influxdb:2.6.1-alpine
  armhf: docker.io/library/influxdb:2.6.1-alpine
  armv7: docker.io/library/influxdb:2.6.1-alpine
  i386: docker.io/library/influxdb:2.6.1-alpine