---
name: "InfluxDB 2"
description: "InfluxDB2 support for Home Assistant"
version: "1.0.0"
slug: "influxdb2"
init: false
arch: 
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8086/tcp: 8086
webui: http://[HOST]:[PORT:8086]
